spring:
  application:
    name: spring-batch-tutorial
  
  # Database Configuration for Kubernetes
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
  
  # Batch Configuration
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
    job-repository:
      table-prefix: BATCH_
  
  # Spring Cloud Task Configuration
  cloud:
    task:
      execution:
        events:
          enabled: true
        cleanup:
          on-task-end: true
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              default:
                namespace: default
                imagePullPolicy: IfNotPresent
                imagePullSecret: ""
                limits:
                  memory: 1024Mi
                  cpu: 1000m
                requests:
                  memory: 512Mi
                  cpu: 500m
  
  # Actuator Configuration
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,batch-jobs,batch-job-executions,task-executions
    endpoint:
      health:
        show-details: always
      batch-jobs:
        enabled: true
      batch-job-executions:
        enabled: true
      task-executions:
        enabled: true

# Logging Configuration
logging:
  level:
    com.example.springbatchtutorial: INFO
    org.springframework.batch: INFO
    org.springframework.cloud.task: INFO
    org.springframework.cloud.dataflow: INFO
    org.hibernate: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server Configuration
server:
  port: 8080

# Batch Configuration
batch:
  csv:
    file:
      path: /app/input/persons.csv

# Task Configuration for SCDF
task:
  execution:
    events:
      enabled: true
    cleanup:
      on-task-end: true
